/-
Copyright (c) 2026 Disk Rigidity Authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Disk Rigidity Authors
-/

module

public import DiskRigidity.Operator.BoundaryDecomposition
public import DiskRigidity.Operator.FoundationDirectSum
public import DiskRigidity.Operator.FoundationUnitary
public import Mathlib.Analysis.InnerProductSpace.PiL2
public import Mathlib.Analysis.InnerProductSpace.ProdL2

/-!
# Matrix coordinates on the interior spectral summand

The boundary-eigenvector decomposition is initially coordinate free.  This
file places its orthogonal complement in an orthonormal Euclidean basis, so
that the remaining operator is again an ordinary finite complex matrix.
-/

@[expose] public section

noncomputable section

open scoped InnerProductSpace Matrix Matrix.Norms.L2Operator

namespace DiskRigidity.Operator

variable {n : Type*} [Fintype n] [DecidableEq n] [Nonempty n]

/-- The reducing span generated by all boundary eigenvectors. -/
abbrev boundarySpace (A : SquareMatrix n) := (boundaryEigenspaceSpan A)ᗮᗮ

/-- Its canonical finite coordinate index. -/
abbrev boundarySpaceIndex (A : SquareMatrix n) :=
  Fin (Module.finrank ℂ (boundarySpace A))

/-- The restriction of `A` to its boundary-eigenvector span. -/
def boundarySpaceOperator (A : SquareMatrix n) :
    boundarySpace A →L[ℂ] boundarySpace A :=
  ((euclideanOperator A).domRestrict (boundarySpace A)).codRestrict
    (boundarySpace A)
    (fun x ↦ by
      change euclideanOperator A (x : EuclideanVector n) ∈ boundarySpace A
      have hx : (x : EuclideanVector n) ∈ boundaryEigenspaceSpan A := by
        simpa only [boundarySpace, Submodule.orthogonal_orthogonal] using x.property
      have hAx := map_boundaryEigenspaceSpan_le A ⟨x, hx, rfl⟩
      change euclideanOperator A (x : EuclideanVector n) ∈
        boundaryEigenspaceSpan A at hAx
      simpa only [boundarySpace, Submodule.orthogonal_orthogonal] using hAx)

/-- Canonical orthonormal coordinates on the boundary summand. -/
def boundarySpaceCoordinates (A : SquareMatrix n) :
    boundarySpace A ≃ₗᵢ[ℂ] EuclideanVector (boundarySpaceIndex A) :=
  (stdOrthonormalBasis ℂ (boundarySpace A)).repr

/-- The diagonal/normal boundary summand as a finite matrix. -/
def boundarySpaceMatrix (A : SquareMatrix n) :
    SquareMatrix (boundarySpaceIndex A) :=
  letI : CompleteSpace (boundarySpace A) :=
    FiniteDimensional.complete ℂ (boundarySpace A)
  euclideanOperator.symm
    ((boundarySpaceCoordinates A).conjStarAlgEquiv (boundarySpaceOperator A))

omit [Nonempty n] in
@[simp]
theorem euclideanOperator_boundarySpaceMatrix (A : SquareMatrix n) :
    euclideanOperator (boundarySpaceMatrix A) =
      ((boundarySpaceCoordinates A) : boundarySpace A →L[ℂ]
          EuclideanVector (boundarySpaceIndex A)) ∘L
        boundarySpaceOperator A ∘L
        ((boundarySpaceCoordinates A).symm :
          EuclideanVector (boundarySpaceIndex A) →L[ℂ] boundarySpace A) := by
  simp only [boundarySpaceMatrix]
  apply ContinuousLinearMap.ext
  intro x
  rw [euclideanOperator.apply_symm_apply]
  rw [LinearIsometryEquiv.conjStarAlgEquiv_apply_apply]
  rfl

omit [Nonempty n] in
@[simp]
theorem boundarySpaceOperator_apply (A : SquareMatrix n)
    (x : boundarySpace A) :
    (boundarySpaceOperator A x : EuclideanVector n) = euclideanOperator A x :=
  rfl

/-- The restriction of the adjoint to the same reducing boundary summand. -/
def boundarySpaceAdjointOperator (A : SquareMatrix n)
    (hInt : (interior (numericalRange A)).Nonempty) :
    boundarySpace A →L[ℂ] boundarySpace A :=
  ((euclideanOperator Aᴴ).domRestrict (boundarySpace A)).codRestrict
    (boundarySpace A)
    (fun x ↦ by
      change euclideanOperator Aᴴ (x : EuclideanVector n) ∈ boundarySpace A
      have hx : (x : EuclideanVector n) ∈ boundaryEigenspaceSpan A := by
        simpa only [boundarySpace, Submodule.orthogonal_orthogonal] using x.property
      have hAx := map_conjTranspose_boundaryEigenspaceSpan_le A hInt
        ⟨x, hx, rfl⟩
      change euclideanOperator Aᴴ (x : EuclideanVector n) ∈
        boundaryEigenspaceSpan A at hAx
      simpa only [boundarySpace, Submodule.orthogonal_orthogonal] using hAx)

omit [Nonempty n] in
@[simp]
theorem boundarySpaceAdjointOperator_apply
    (A : SquareMatrix n) (hInt : (interior (numericalRange A)).Nonempty)
    (x : boundarySpace A) :
    (boundarySpaceAdjointOperator A hInt x : EuclideanVector n) =
      euclideanOperator Aᴴ x :=
  rfl

omit [Nonempty n] in
/-- Restricting the full adjoint is the Hilbert-space adjoint of the
restricted boundary operator. -/
theorem boundarySpaceAdjointOperator_eq_adjoint
    (A : SquareMatrix n) (hInt : (interior (numericalRange A)).Nonempty) :
    boundarySpaceAdjointOperator A hInt =
      (boundarySpaceOperator A).adjoint := by
  apply ContinuousLinearMap.ext
  intro x
  apply ext_inner_left ℂ
  intro y
  rw [(boundarySpaceOperator A).adjoint_inner_right]
  change ⟪(y : EuclideanVector n), euclideanOperator Aᴴ x⟫_ℂ =
    ⟪euclideanOperator A y, (x : EuclideanVector n)⟫_ℂ
  rw [euclideanOperator_conjTranspose]
  exact (euclideanOperator A).adjoint_inner_right y x

omit [Nonempty n] in
/-- The boundary spectral summand is normal. -/
theorem isStarNormal_boundarySpaceOperator
    (A : SquareMatrix n) (hInt : (interior (numericalRange A)).Nonempty) :
    IsStarNormal (boundarySpaceOperator A) := by
  have hops : ∀ z : boundarySpace A,
      boundarySpaceAdjointOperator A hInt (boundarySpaceOperator A z) =
        boundarySpaceOperator A (boundarySpaceAdjointOperator A hInt z) := by
    intro z
    have hz' : (z : EuclideanVector n) ∈ boundaryEigenspaceSpan A := by
      simpa only [boundarySpace, Submodule.orthogonal_orthogonal] using z.property
    have hz : (z : EuclideanVector n) ∈
        Submodule.span ℂ (boundaryEigenvectors A) := by
      simpa only [boundaryEigenspaceSpan] using hz'
    have hzcomm :
        euclideanOperator Aᴴ (euclideanOperator A (z : EuclideanVector n)) =
          euclideanOperator A (euclideanOperator Aᴴ (z : EuclideanVector n)) := by
      refine Submodule.span_induction
        (p := fun w _ ↦ euclideanOperator Aᴴ (euclideanOperator A w) =
          euclideanOperator A (euclideanOperator Aᴴ w)) ?_ ?_ ?_ ?_ hz
      · intro x hx
        let lambda : ℂ := Classical.choose hx.2
        have hAx : euclideanOperator A x = lambda • x :=
          (Classical.choose_spec hx.2).2
        have hAstarx : euclideanOperator Aᴴ x = star lambda • x :=
          euclideanOperator_conjTranspose_eq_smul_of_mem_boundaryEigenvectors
            A hInt hx
        rw [hAx, hAstarx, map_smul, map_smul, hAx, hAstarx]
        simp only [smul_smul]
        rw [mul_comm]
      · simp
      · intro x y hx hy hxeq hyeq
        simpa only [map_add] using congrArg₂ (· + ·) hxeq hyeq
      · intro c x hx hxeq
        simpa only [map_smul, smul_smul] using congrArg (fun w ↦ c • w) hxeq
    apply Subtype.ext
    simpa only [boundarySpaceOperator_apply,
      boundarySpaceAdjointOperator_apply] using hzcomm
  rw [isStarNormal_iff, commute_iff_eq]
  rw [show star (boundarySpaceOperator A) =
      boundarySpaceAdjointOperator A hInt by
        exact (boundarySpaceAdjointOperator_eq_adjoint A hInt).symm]
  apply ContinuousLinearMap.ext
  exact hops

omit [Nonempty n] in
/-- Normality of the boundary summand in its canonical matrix coordinates. -/
theorem isStarNormal_boundarySpaceMatrix
    (A : SquareMatrix n) (hInt : (interior (numericalRange A)).Nonempty) :
    IsStarNormal (boundarySpaceMatrix A) := by
  have hnormal : IsStarNormal (boundarySpaceOperator A) :=
    isStarNormal_boundarySpaceOperator A hInt
  have hnormal' : IsStarNormal
      ((boundarySpaceCoordinates A).conjStarAlgEquiv
        (boundarySpaceOperator A)) :=
    IsStarNormal.map (hr := hnormal)
      (boundarySpaceCoordinates A).conjStarAlgEquiv
      (boundarySpaceOperator A)
  simpa only [boundarySpaceMatrix] using
    (IsStarNormal.map (hr := hnormal') euclideanOperator.symm
      ((boundarySpaceCoordinates A).conjStarAlgEquiv
        (boundarySpaceOperator A)))

/-- The reducing summand left after all boundary eigenvectors are removed. -/
abbrev boundaryComplement (A : SquareMatrix n) :=
  (boundaryEigenspaceSpan A)ᗮ

/-- Its canonical finite coordinate index. -/
abbrev boundaryComplementIndex (A : SquareMatrix n) :=
  Fin (Module.finrank ℂ (boundaryComplement A))

/-- The restriction of `A` to the reducing orthogonal complement. -/
def boundaryComplementOperator (A : SquareMatrix n)
    (hInt : (interior (numericalRange A)).Nonempty) :
    boundaryComplement A →L[ℂ] boundaryComplement A :=
  ((euclideanOperator A).domRestrict (boundaryComplement A)).codRestrict
    (boundaryComplement A)
    (fun x ↦ map_boundaryEigenspaceSpan_orthogonal_le A hInt
      ⟨x, x.property, rfl⟩)

/-- Canonical orthonormal coordinates on the complement. -/
def boundaryComplementCoordinates (A : SquareMatrix n) :
    boundaryComplement A ≃ₗᵢ[ℂ]
      EuclideanVector (boundaryComplementIndex A) :=
  (stdOrthonormalBasis ℂ (boundaryComplement A)).repr

/-- The matrix of the remaining interior spectral summand. -/
def boundaryComplementMatrix (A : SquareMatrix n)
    (hInt : (interior (numericalRange A)).Nonempty) :
    SquareMatrix (boundaryComplementIndex A) :=
  euclideanOperator.symm
    ((boundaryComplementCoordinates A).conjStarAlgEquiv
      (boundaryComplementOperator A hInt))

/-- The orthogonal complement of the double-orthogonal boundary space, in
the canonical coordinates of `boundaryComplement`. -/
def boundarySpaceOrthogonalCoordinates (A : SquareMatrix n) :
    (boundarySpace A)ᗮ ≃ₗᵢ[ℂ]
      EuclideanVector (boundaryComplementIndex A) :=
  (LinearIsometryEquiv.ofEq (boundarySpace A)ᗮ (boundaryComplement A) (by
      simp only [boundarySpace, boundaryComplement,
        Submodule.orthogonal_orthogonal])).trans
    (boundaryComplementCoordinates A)

/-- Canonical orthonormal coordinates adapted to the reducing decomposition
into the boundary spectral summand and its orthogonal complement. -/
def boundaryDecompositionCoordinates (A : SquareMatrix n) :
    EuclideanVector n ≃ₗᵢ[ℂ]
      EuclideanVector
        (boundarySpaceIndex A ⊕ boundaryComplementIndex A) :=
  (Submodule.orthogonalDecomposition (boundarySpace A)).trans <|
    (LinearIsometryEquiv.withLpProdCongr 2
      (boundarySpaceCoordinates A)
      (boundarySpaceOrthogonalCoordinates A)).trans <|
        (PiLp.sumPiLpEquivProdLpPiLp 2 (fun _ ↦ ℂ)).symm

/-- The original matrix in coordinates adapted to the boundary/complement
decomposition. -/
def boundaryDecompositionMatrix (A : SquareMatrix n) :
    SquareMatrix
      (boundarySpaceIndex A ⊕ boundaryComplementIndex A) :=
  euclideanOperator.symm
    ((boundaryDecompositionCoordinates A).conjStarAlgEquiv
      (euclideanOperator A))

omit [Nonempty n] in
@[simp]
theorem euclideanOperator_boundaryDecompositionMatrix (A : SquareMatrix n) :
    euclideanOperator (boundaryDecompositionMatrix A) =
      (boundaryDecompositionCoordinates A).conjStarAlgEquiv
        (euclideanOperator A) := by
  simp [boundaryDecompositionMatrix]

omit [Nonempty n] in
@[simp]
theorem euclideanOperator_boundaryComplementMatrix
    (A : SquareMatrix n) (hInt : (interior (numericalRange A)).Nonempty) :
    euclideanOperator (boundaryComplementMatrix A hInt) =
      (boundaryComplementCoordinates A).conjStarAlgEquiv
        (boundaryComplementOperator A hInt) := by
  simp [boundaryComplementMatrix]

omit [Nonempty n] in
@[simp]
theorem boundaryComplementOperator_apply
    (A : SquareMatrix n) (hInt : (interior (numericalRange A)).Nonempty)
    (x : boundaryComplement A) :
    (boundaryComplementOperator A hInt x : EuclideanVector n) =
      euclideanOperator A x :=
  rfl

omit [Nonempty n] in
/-- In the adapted orthonormal coordinates, `A` is exactly the direct sum of
its normal boundary block and its interior spectral block. -/
theorem boundaryDecompositionMatrix_eq_matrixDirectSum
    (A : SquareMatrix n) (hInt : (interior (numericalRange A)).Nonempty) :
    boundaryDecompositionMatrix A =
      matrixDirectSum (boundarySpaceMatrix A)
        (boundaryComplementMatrix A hInt) := by
  apply euclideanOperator.injective
  change euclideanOperator (boundaryDecompositionMatrix A) =
    euclideanOperator
      (matrixDirectSum (boundarySpaceMatrix A)
        (boundaryComplementMatrix A hInt))
  rw [euclideanOperator_boundaryDecompositionMatrix]
  apply ContinuousLinearMap.ext
  intro x
  rw [LinearIsometryEquiv.conjStarAlgEquiv_apply_apply]
  apply (boundaryDecompositionCoordinates A).symm.injective
  rw [(boundaryDecompositionCoordinates A).symm_apply_apply]
  have hfst : ∀ y : EuclideanVector
      (boundarySpaceIndex A ⊕ boundaryComplementIndex A),
      ((PiLp.sumPiLpEquivProdLpPiLp (𝕜 := ℂ) 2 (fun _ ↦ ℂ)) y).fst =
        sumVectorLeft y := fun _ ↦ rfl
  have hsnd : ∀ y : EuclideanVector
      (boundarySpaceIndex A ⊕ boundaryComplementIndex A),
      ((PiLp.sumPiLpEquivProdLpPiLp (𝕜 := ℂ) 2 (fun _ ↦ ℂ)) y).snd =
        sumVectorRight y := fun _ ↦ rfl
  simp [boundaryDecompositionCoordinates,
    boundarySpaceOrthogonalCoordinates, hfst, hsnd,
    euclideanOperator_boundarySpaceMatrix,
    euclideanOperator_boundaryComplementMatrix]

omit [Nonempty n] in
/-- The adapted coordinate matrix has exactly the same numerical range as
the original matrix. -/
theorem numericalRange_boundaryDecompositionMatrix (A : SquareMatrix n) :
    numericalRange (boundaryDecompositionMatrix A) = numericalRange A := by
  let e := boundaryDecompositionCoordinates A
  ext z
  constructor
  · rintro ⟨x, hx, rfl⟩
    refine ⟨e.symm x, e.symm.norm_map x |>.trans hx, ?_⟩
    rw [euclideanOperator_boundaryDecompositionMatrix,
      LinearIsometryEquiv.conjStarAlgEquiv_apply_apply]
    have hinner := e.inner_map_map (e.symm x)
      (euclideanOperator A (e.symm x))
    simpa only [e, LinearIsometryEquiv.apply_symm_apply] using hinner.symm
  · rintro ⟨x, hx, rfl⟩
    refine ⟨e x, e.norm_map x |>.trans hx, ?_⟩
    rw [euclideanOperator_boundaryDecompositionMatrix,
      LinearIsometryEquiv.conjStarAlgEquiv_apply_apply]
    have hinner := e.inner_map_map x (euclideanOperator A x)
    simpa only [e, LinearIsometryEquiv.symm_apply_apply] using hinner

omit [Nonempty n] in
/-- Polynomial evaluation is transported by the adapted orthonormal
coordinates. -/
theorem euclideanOperator_polynomialEval_boundaryDecompositionMatrix
    (A : SquareMatrix n) (p : Polynomial ℂ) :
    euclideanOperator (polynomialEval p (boundaryDecompositionMatrix A)) =
      (boundaryDecompositionCoordinates A).conjStarAlgEquiv
        (euclideanOperator (polynomialEval p A)) := by
  rw [euclideanOperator_polynomialEval,
    euclideanOperator_boundaryDecompositionMatrix,
    euclideanOperator_polynomialEval]
  have h := Polynomial.aeval_algHom
    ((boundaryDecompositionCoordinates A).conjStarAlgEquiv.toAlgEquiv.toAlgHom)
      (euclideanOperator A)
  exact AlgHom.congr_fun h p

omit [Nonempty n] in
/-- Adapted orthonormal coordinates preserve every polynomial operator
norm. -/
theorem norm_polynomialEval_boundaryDecompositionMatrix
    (A : SquareMatrix n) (p : Polynomial ℂ) :
    ‖polynomialEval p (boundaryDecompositionMatrix A)‖ =
      ‖polynomialEval p A‖ := by
  rw [matrix_norm_eq_operator_norm, matrix_norm_eq_operator_norm,
    euclideanOperator_polynomialEval_boundaryDecompositionMatrix]
  exact StarAlgEquiv.norm_map
    (boundaryDecompositionCoordinates A).conjStarAlgEquiv
      (euclideanOperator (polynomialEval p A))

omit [Nonempty n] in
/-- Adapted orthonormal coordinates preserve the polynomial maximum on the
numerical range. -/
theorem maxPolynomialModulus_boundaryDecompositionMatrix
    (A : SquareMatrix n) (p : Polynomial ℂ) :
    maxPolynomialModulus (boundaryDecompositionMatrix A) p =
      maxPolynomialModulus A p := by
  simp only [maxPolynomialModulus,
    numericalRange_boundaryDecompositionMatrix]

omit [Nonempty n] in
/-- Unit vectors in the complement retain their numerical values in the
original space. -/
theorem inner_boundaryComplementOperator
    (A : SquareMatrix n) (hInt : (interior (numericalRange A)).Nonempty)
    (x : boundaryComplement A) :
    ⟪x, boundaryComplementOperator A hInt x⟫_ℂ =
      ⟪(x : EuclideanVector n), euclideanOperator A x⟫_ℂ :=
  rfl

omit [Nonempty n] in
/-- The numerical range of the boundary block is contained in the original
numerical range. -/
theorem numericalRange_boundarySpaceMatrix_subset (A : SquareMatrix n) :
    numericalRange (boundarySpaceMatrix A) ⊆ numericalRange A := by
  rintro z ⟨x, hx, rfl⟩
  let e := boundarySpaceCoordinates A
  let u : boundarySpace A := e.symm x
  refine ⟨(u : EuclideanVector n), ?_, ?_⟩
  · change ‖u‖ = 1
    exact e.symm.norm_map x |>.trans hx
  · rw [euclideanOperator_boundarySpaceMatrix]
    simp only [ContinuousLinearMap.comp_apply]
    have heinner := e.inner_map_map (𝕜 := ℂ) u (boundarySpaceOperator A u)
    simpa [e, u, boundarySpaceOperator_apply] using heinner.symm

omit [Nonempty n] in
/-- The numerical range of the compressed matrix is contained in the
original numerical range. -/
theorem numericalRange_boundaryComplementMatrix_subset
    (A : SquareMatrix n) (hInt : (interior (numericalRange A)).Nonempty) :
    numericalRange (boundaryComplementMatrix A hInt) ⊆ numericalRange A := by
  rintro z ⟨x, hx, rfl⟩
  let e := boundaryComplementCoordinates A
  let u : boundaryComplement A := e.symm x
  refine ⟨(u : EuclideanVector n), ?_, ?_⟩
  · change ‖u‖ = 1
    exact e.symm.norm_map x |>.trans hx
  · rw [euclideanOperator_boundaryComplementMatrix,
      LinearIsometryEquiv.conjStarAlgEquiv_apply_apply]
    have heinner := e.inner_map_map u (boundaryComplementOperator A hInt u)
    simpa [e, u, inner_boundaryComplementOperator] using heinner.symm

/-- The polynomial norm on the normal boundary block is bounded by the
maximum modulus on the original numerical range.  The zero-dimensional
boundary block is included. -/
theorem norm_polynomialEval_boundarySpaceMatrix_le
    (A : SquareMatrix n) (hInt : (interior (numericalRange A)).Nonempty)
    (p : Polynomial ℂ) :
    ‖polynomialEval p (boundarySpaceMatrix A)‖ ≤
      maxPolynomialModulus A p := by
  rcases isEmpty_or_nonempty (boundarySpaceIndex A) with hempty | hnonempty
  · let _ : IsEmpty (boundarySpaceIndex A) := hempty
    have hzero : polynomialEval p (boundarySpaceMatrix A) = 0 := by
      ext i
      exact isEmptyElim i
    rw [hzero, norm_zero]
    exact maxPolynomialModulus_nonneg A p
  · let _ : Nonempty (boundarySpaceIndex A) := hnonempty
    have hnormal := isStarNormal_boundarySpaceMatrix A hInt
    refine (norm_polynomialEval_le_maxPolynomialModulus_of_isStarNormal
      (boundarySpaceMatrix A) hnormal p).trans ?_
    obtain ⟨z, hz, hmax⟩ :=
      exists_norm_eval_eq_maxPolynomialModulus (boundarySpaceMatrix A) p
    rw [← hmax]
    exact norm_eval_le_maxPolynomialModulus A p
      (numericalRange_boundarySpaceMatrix_subset A hz)

/-- After the normal boundary block is peeled away, every polynomial norm
of `A` is bounded by the larger of the scalar maximum and the corresponding
norm on the interior spectral block. -/
theorem norm_polynomialEval_le_max_boundaryComplement
    (A : SquareMatrix n) (hInt : (interior (numericalRange A)).Nonempty)
    (p : Polynomial ℂ) :
    ‖polynomialEval p A‖ ≤
      max (maxPolynomialModulus A p)
        ‖polynomialEval p (boundaryComplementMatrix A hInt)‖ := by
  calc
    ‖polynomialEval p A‖ =
        ‖polynomialEval p (boundaryDecompositionMatrix A)‖ :=
      (norm_polynomialEval_boundaryDecompositionMatrix A p).symm
    _ = ‖polynomialEval p
        (matrixDirectSum (boundarySpaceMatrix A)
          (boundaryComplementMatrix A hInt))‖ := by
      rw [boundaryDecompositionMatrix_eq_matrixDirectSum]
    _ = ‖matrixDirectSum
        (polynomialEval p (boundarySpaceMatrix A))
        (polynomialEval p (boundaryComplementMatrix A hInt))‖ := by
      rw [polynomialEval_matrixDirectSum]
    _ ≤ max ‖polynomialEval p (boundarySpaceMatrix A)‖
        ‖polynomialEval p (boundaryComplementMatrix A hInt)‖ :=
      norm_matrixDirectSum_le_max _ _
    _ ≤ max (maxPolynomialModulus A p)
        ‖polynomialEval p (boundaryComplementMatrix A hInt)‖ :=
      max_le_max_right _ (norm_polynomialEval_boundarySpaceMatrix_le A hInt p)

omit [Nonempty n] in
/-- Every spectral value of the compressed matrix lies in the interior of
the original numerical range. -/
theorem spectrum_boundaryComplementMatrix_subset_interior
    (A : SquareMatrix n) (hInt : (interior (numericalRange A)).Nonempty) :
    spectrum ℂ (boundaryComplementMatrix A hInt) ⊆
      interior (numericalRange A) := by
  intro lambda hlambda
  let B := boundaryComplementMatrix A hInt
  have heig : Module.End.HasEigenvalue (Matrix.toEuclideanLin B) lambda := by
    rw [Module.End.hasEigenvalue_iff_mem_spectrum]
    simpa only [Matrix.spectrum_toLpLin] using hlambda
  obtain ⟨v, hv⟩ := heig.exists_hasEigenvector
  let e := boundaryComplementCoordinates A
  let u : boundaryComplement A := e.symm v
  have hu0 : u ≠ 0 := by
    intro hu
    apply hv.2
    change v = 0
    rw [← e.apply_symm_apply v, show e.symm v = u by rfl, hu]
    simp
  have hBv : euclideanOperator B v = lambda • v := hv.apply_eq_smul
  have hcoord : e (boundaryComplementOperator A hInt u) = lambda • v := by
    rw [show euclideanOperator B =
      e.conjStarAlgEquiv (boundaryComplementOperator A hInt) by
        exact euclideanOperator_boundaryComplementMatrix A hInt] at hBv
    simpa [e, u, LinearIsometryEquiv.conjStarAlgEquiv_apply_apply] using hBv
  have hTu : boundaryComplementOperator A hInt u = lambda • u := by
    apply e.injective
    rw [hcoord, map_smul, e.apply_symm_apply]
  have hAu : euclideanOperator A (u : EuclideanVector n) =
      lambda • (u : EuclideanVector n) := by
    have := congrArg Subtype.val hTu
    simpa only [boundaryComplementOperator_apply, Submodule.coe_smul_of_tower]
      using this
  exact eigenvalue_mem_interior_of_mem_boundaryEigenspaceSpan_orthogonal
    A u.property (Subtype.coe_ne_coe.mpr hu0) hAu

omit [Nonempty n] in
/-- If the boundary-eigenvector span exhausts the space, the matrix is
normal. -/
theorem isStarNormal_of_boundaryEigenspaceSpan_eq_top
    (A : SquareMatrix n) (hInt : (interior (numericalRange A)).Nonempty)
    (hspan : boundaryEigenspaceSpan A = ⊤) : IsStarNormal A := by
  have hops : ∀ z : EuclideanVector n,
      euclideanOperator Aᴴ (euclideanOperator A z) =
        euclideanOperator A (euclideanOperator Aᴴ z) := by
    intro z
    have hz : z ∈ Submodule.span ℂ (boundaryEigenvectors A) := by
      change z ∈ boundaryEigenspaceSpan A
      rw [hspan]
      trivial
    refine Submodule.span_induction
      (p := fun w _ ↦ euclideanOperator Aᴴ (euclideanOperator A w) =
        euclideanOperator A (euclideanOperator Aᴴ w)) ?_ ?_ ?_ ?_ hz
    · intro x hx
      let lambda : ℂ := Classical.choose hx.2
      have hAx : euclideanOperator A x = lambda • x :=
        (Classical.choose_spec hx.2).2
      have hAstarx : euclideanOperator Aᴴ x = star lambda • x :=
        euclideanOperator_conjTranspose_eq_smul_of_mem_boundaryEigenvectors
          A hInt hx
      rw [hAx, hAstarx, map_smul, map_smul, hAx, hAstarx]
      simp only [smul_smul]
      rw [mul_comm]
    · simp
    · intro x y hx hy hxeq hyeq
      simpa only [map_add] using congrArg₂ (· + ·) hxeq hyeq
    · intro c x hx hxeq
      simpa only [map_smul, smul_smul] using congrArg (fun w ↦ c • w) hxeq
  rw [isStarNormal_iff, commute_iff_eq]
  apply euclideanOperator.injective
  have hstar : star A = Aᴴ := rfl
  calc
    euclideanOperator (star A * A) =
        euclideanOperator Aᴴ * euclideanOperator A := by rw [hstar, map_mul]
    _ = euclideanOperator A * euclideanOperator Aᴴ := by
      apply ContinuousLinearMap.ext
      intro z
      exact hops z
    _ = euclideanOperator (A * star A) := by rw [hstar, map_mul]

/-- At extremal constant two, a nonzero complement remains after peeling
the normal boundary summand. -/
theorem nonempty_boundaryComplementIndex_of_crouzeixConstant_eq_two
    (A : SquareMatrix n) (hInt : (interior (numericalRange A)).Nonempty)
    (hpsi : crouzeixConstant A = 2) :
    Nonempty (boundaryComplementIndex A) := by
  have hspan : boundaryEigenspaceSpan A ≠ ⊤ := by
    intro htop
    have hnormal := isStarNormal_of_boundaryEigenspaceSpan_eq_top A hInt htop
    have hone := crouzeixConstant_eq_one_of_isStarNormal A hnormal
    linarith
  have hperp : boundaryComplement A ≠ ⊥ := by
    intro hbot
    exact hspan (Submodule.orthogonal_eq_bot_iff.mp hbot)
  obtain ⟨u, hu, hu0⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hperp
  let _ : Nontrivial (boundaryComplement A) := by
    refine ⟨⟨⟨u, hu⟩, 0, ?_⟩⟩
    intro h
    apply hu0
    exact congrArg Subtype.val h
  exact Fin.pos_iff_nonempty.mp Module.finrank_pos

end DiskRigidity.Operator
